package kh.farrukh.progee_api.endpoints.role;

public enum Permission {

    // TODO: 8/11/22 add permissions for upvote/downvote review (with unit and int tests)

    CAN_VIEW_LANGUAGES_BY_STATE,
    CAN_CREATE_LANGUAGE,
    CAN_UPDATE_OWN_LANGUAGE,
    CAN_UPDATE_OTHERS_LANGUAGE,
    CAN_SET_LANGUAGE_STATE,
    CAN_DELETE_LANGUAGE,

    CAN_VIEW_FRAMEWORKS_BY_STATE,
    CAN_CREATE_FRAMEWORK,
    CAN_UPDATE_OWN_FRAMEWORK,
    CAN_UPDATE_OTHERS_FRAMEWORK,
    CAN_SET_FRAMEWORK_STATE,
    CAN_DELETE_FRAMEWORK,

    CAN_CREATE_REVIEW,
    CAN_UPDATE_OWN_REVIEW,
    CAN_UPDATE_OTHERS_REVIEW,
    CAN_DELETE_OWN_REVIEW,
    CAN_DELETE_OTHERS_REVIEW,

    CAN_UPDATE_OWN_USER,
    CAN_UPDATE_OTHER_USER,
    CAN_DELETE_USER,

    CAN_VIEW_ROLE,
    CAN_CREATE_ROLE,
    CAN_UPDATE_ROLE,
    CAN_SET_USER_ROLE,
    CAN_DELETE_ROLE,

    CAN_UPDATE_IMAGE,
    CAN_DELETE_IMAGE
}