package kh.farrukh.progee_api.endpoints.role;

public enum Permission {

    CAN_VIEW_LANGUAGE,
    CAN_CREATE_LANGUAGE,
    CAN_UPDATE_LANGUAGE,
    CAN_DELETE_LANGUAGE,

    CAN_VIEW_FRAMEWORK,
    CAN_CREATE_FRAMEWORK,
    CAN_UPDATE_FRAMEWORK,
    CAN_DELETE_FRAMEWORK,

    CAN_VIEW_REVIEW,
    CAN_CREATE_REVIEW,
    CAN_UPDATE_REVIEW,
    CAN_DELETE_REVIEW,

    CAN_VIEW_USER,
    CAN_UPDATE_USER,
    CAN_DELETE_USER,

    CAN_VIEW_ROLE,
    CAN_CREATE_ROLE,
    CAN_UPDATE_ROLE,
    CAN_DELETE_ROLE,

    CAN_VIEW_IMAGE,
    CAN_CREATE_IMAGE,
    CAN_UPDATE_IMAGE,
    CAN_DELETE_IMAGE
}
