spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/progee_api
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: strings
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  flyway:
    placeholders:
      DEFAULT_ENCRYPTED_PASSWORD: ${DEFAULT_ENCRYPTED_PASSWORD:$2a$10$u.olISwSqjbaZCHADL0fIuw7eBijpqzvfSavgXnPcfniJTwORGNvm}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: us-east-1
    stack:
      auto: false

aws:
  s3:
    bucket: progee-api-v1

jwt:
  secret: ${JWT_SECRET:secret}
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

server:
  error:
    include-stacktrace: never