CREATE TABLE frameworks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    state       VARCHAR(255),
    description VARCHAR(255),
    name        VARCHAR(255),
    author_id   BIGINT,
    image_id    BIGINT,
    language_id BIGINT,
    CONSTRAINT frameworks_pkey PRIMARY KEY (id)
);

CREATE TABLE image
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content BYTEA,
    CONSTRAINT image_pkey PRIMARY KEY (id)
);

CREATE TABLE languages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    state       VARCHAR(255),
    description VARCHAR(255),
    name        VARCHAR(255),
    author_id   BIGINT,
    image_id    BIGINT,
    CONSTRAINT languages_pkey PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    body         VARCHAR(255),
    review_value INTEGER,
    author_id    BIGINT,
    language_id  BIGINT,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    is_enabled BOOLEAN,
    is_locked  BOOLEAN,
    name       VARCHAR(255),
    password   VARCHAR(255),
    role       VARCHAR(255),
    username   VARCHAR(255),
    image_id   BIGINT,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE frameworks
    ADD CONSTRAINT uk_hjbth9dc342cn7dqo0l2s1ftq UNIQUE (name);

ALTER TABLE languages
    ADD CONSTRAINT uk_f6axmaokhmrbmm746866v0uyu UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username);

CREATE TABLE review_down_votes
(
    review_id  BIGINT NOT NULL,
    down_votes BIGINT
);

CREATE TABLE review_up_votes
(
    review_id BIGINT NOT NULL,
    up_votes  BIGINT
);

ALTER TABLE review_up_votes
    ADD CONSTRAINT fk2hog4j8bngr0xh1wvs9rg027j FOREIGN KEY (review_id) REFERENCES reviews (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reviews
    ADD CONSTRAINT fk4vb9m2r45v0hcmdmjd8fo681q FOREIGN KEY (language_id) REFERENCES languages (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE review_down_votes
    ADD CONSTRAINT fkgt4md3q75fjt1k3pwt5a187v4 FOREIGN KEY (review_id) REFERENCES reviews (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE languages
    ADD CONSTRAINT fkhy7pj978ly64ydmodlbgdewkw FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users
    ADD CONSTRAINT fklqj25c28swu46s4jbudd7hore FOREIGN KEY (image_id) REFERENCES image (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE frameworks
    ADD CONSTRAINT fkm4ga66uiqf2rt6ynucwwb1c83 FOREIGN KEY (image_id) REFERENCES image (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE languages
    ADD CONSTRAINT fkn1gk8lkuf5dv0it3p1law4i9t FOREIGN KEY (image_id) REFERENCES image (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE frameworks
    ADD CONSTRAINT fkqy32p17da1r14yq2ir757adnu FOREIGN KEY (language_id) REFERENCES languages (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reviews
    ADD CONSTRAINT fkse5kx11600wtv0jh9jobvrdpi FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE frameworks
    ADD CONSTRAINT fkt04ku5b48w1arfncfecypnlic FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;