TRUNCATE TABLE reviews CASCADE;
TRUNCATE TABLE review_up_votes CASCADE;
TRUNCATE TABLE review_down_votes CASCADE;
TRUNCATE TABLE frameworks CASCADE;
TRUNCATE TABLE languages CASCADE;
TRUNCATE TABLE users CASCADE;
