name: Publish Docker image

on:
  push:
    branches: master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Set up Java 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'
      - name: Build and push
        run: |
          IMAGE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          REPOSITORY=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout | tr '[:upper:]' '[:lower:]')
          mvn --batch-mode clean package -DskipTests
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/${REPOSITORY}:${IMAGE_VERSION} --tag ${{ secrets.DOCKER_USERNAME }}/${REPOSITORY}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${REPOSITORY}:${IMAGE_VERSION} && docker push ${{ secrets.DOCKER_USERNAME }}/${REPOSITORY}:latest