name: Upload artifact to GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    name: Upload artifact
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Set up Java 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode package -DskipTests
      - name: Upload JAVA artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: target/*.jar