name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for your first issue. I appreciate it! Keep going!"
        pr-message: "Oh, thanks for contributing! You can reach me out if you have any questions or suggestions!"
